include: package:pedantic/analysis_options.yaml
analyzer:
  enable-experiment:
    - non-nullable
  #   - extension-methods
  #exclude: [build/**]
  #strong-mode:
    #implicit-casts: false


linter:
  rules:
    - camel_case_types